spring:

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/stepupz_user-Auth_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key : "uK3m6kA2x8pQ9rV7sB4nC1dW5jH2yZ8gF0eT3vM7rX9qP4lN6mB2oC7kS5wR8tA1"
      expiration: 86400000
  name : user-auth-service
cloud:
  discovery:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true