application:
  security:
    jwt:
      secret-key : "uK3m6kA2x8pQ9rV7sB4nC1dW5jH2yZ8gF0eT3vM7rX9qP4lN6mB2oC7kS5wR8tA1"
      expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
